# Generated by Django 4.2 on 2025-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWorkWebSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_chat',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
