# Generated by Django 4.2 on 2025-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWorkWebSite', '0002_alter_db_chat_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
