# Generated by Django 4.2 on 2025-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWorkWebSite', '0003_alter_db_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/uploads')),
            ],
        ),
    ]
