# Generated by Django 4.2 on 2025-06-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWorkWebSite', '0004_db_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_encCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('countKey', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='db_files',
            name='file',
            field=models.TextField(),
        ),
    ]
